import { Command, Flags, Args } from '@oclif/core';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { logger, printBanner } from '@cloudcart/cli-kit';
import { resolveProjectRoot } from '../../../lib/project.js';

const ROUTE_TEMPLATES: Record<string, { file: string; description: string }> = {
  'products.$handle': { file: 'products.$handle.tsx', description: 'Product detail page' },
  'products._index': { file: 'products._index.tsx', description: 'Products listing' },
  'collections.$handle': { file: 'collections.$handle.tsx', description: 'Collection page' },
  'collections._index': { file: 'collections._index.tsx', description: 'Collections listing' },
  'cart': { file: 'cart.tsx', description: 'Shopping cart' },
  'search': { file: 'search.tsx', description: 'Search page' },
  'pages.$handle': { file: 'pages.$handle.tsx', description: 'CMS pages' },
  'account': { file: 'account.tsx', description: 'Account layout' },
  'account._index': { file: 'account._index.tsx', description: 'Account overview' },
  '[robots.txt]': { file: '[robots.txt].tsx', description: 'Robots.txt generation' },
  '[sitemap.xml]': { file: '[sitemap.xml].tsx', description: 'Sitemap generation' },
};

export default class NitroGenerateRoute extends Command {
  static override description = 'Generate a Nitro route from template';

  static override examples = [
    '<%= config.bin %> nitro generate route products.$handle',
    '<%= config.bin %> nitro generate route cart',
  ];

  static override args = {
    name: Args.string({ description: 'Route name (e.g., products.$handle, cart, search)', required: true }),
  };

  static override flags = {
    force: Flags.boolean({ description: 'Overwrite existing route', default: false }),
    path: Flags.string({ description: 'Path to the Nitro storefront root', default: '.' }),
  };

  async run(): Promise<void> {
    const { args, flags } = await this.parse(NitroGenerateRoute);
    const root = resolveProjectRoot(flags.path);

    printBanner();

    const routesDir = resolve(root, 'app/routes');
    if (!existsSync(routesDir)) mkdirSync(routesDir, { recursive: true });

    const template = ROUTE_TEMPLATES[args.name];
    const fileName = template?.file ?? `${args.name}.tsx`;
    const filePath = resolve(routesDir, fileName);

    if (existsSync(filePath) && !flags.force) {
      logger.warn(`Route "${fileName}" already exists. Use --force to overwrite.`);
      return;
    }

    writeFileSync(filePath, generateRouteContent(args.name));
    logger.success(`Generated route: app/routes/${fileName}`);
  }
}

function generateRouteContent(routeName: string): string {
  const capitalized = routeName
    .replace(/[.$\[\]]/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');

  return `import {useLoaderData} from 'react-router';
import type {Route} from './+types/${ROUTE_TEMPLATES[routeName]?.file.replace('.tsx', '') ?? routeName}';
import {getContext} from '~/lib/context';
import {getSeoMeta} from '@cloudcart/nitro';

export const meta: Route.MetaFunction = () => getSeoMeta({title: '${capitalized} | Nitro'});

export async function loader({context, request}: Route.LoaderArgs) {
  const ctx = await getContext(context, request);
  // TODO: Load data from storefront
  return {};
}

export default function ${capitalized}Route() {
  const data = useLoaderData<typeof loader>();

  return (
    <div>
      <h1>${capitalized}</h1>
      <p>Generated by CloudCart CLI.</p>
    </div>
  );
}
`;
}
